import "@/styles/globals.css";
import type { Metadata } from "next";
import AuthProvider from "./auth/authProvider";

export const metadata: Metadata = {
    title: "IUT TMS",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}
